# Generated by Django 2.1 on 2018-08-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
