# Generated by Django 2.1 on 2018-08-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180824_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
