# Generated by Django 2.1 on 2018-08-28 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_auto_20180826_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(default='Żaden,załaduj go ponownie', upload_to=''),
        ),
    ]
