# Generated by Django 2.1 on 2018-08-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180828_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='group',
            new_name='grupa',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='komentarz',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='nazwa',
        ),
    ]
